version: '3'

volumes:
  .:
  postgres_data:
  static:

services:
  books_psql:
    image: library/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - env

  books_app:
    build: .
    volumes:
      - static:/code/static
      - .:/code
    env_file:
      - env
    depends_on:
      - books_psql

  nginx:
    image: library/nginx
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - books_app
